---
name: Update

'on':
  schedule:
    - cron: '0 0 * * 1,5'  # At 00:00 on Monday, and Friday.
  workflow_dispatch:

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v21

      - run: 'nix flake update'
      - run: 'nix flake check'
      - run: 'nix build .#default'

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'cron(flake): Update inputs'
